server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product-service
          predicates: [ Path=/api/products/** ]
        - id: supplier
          uri: lb://supplier-service
          predicates: [ Path=/api/suppliers/** ]
        - id: inventory
          uri: lb://inventory-service
          predicates: [ Path=/api/inventory/** ]
        - id: order
          uri: lb://order-service
          predicates: [ Path=/api/orders/** ]
        - id: notification
          uri: lb://notification-service
          predicates: [ Path=/api/notifications/**, Path=/internal/notify/** ]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: change-me-change-me-change-me-32-bytes-minimum
  issuer: inventory
  exp-min: 120
